### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by pytkin**
### Update dependencies:

- update `webpack` from 1.13.1 to 5.16
- update `gulp` from 3.9.1 to 4.0.2
- update `babel` from 6 to 7.12.10
- update other minor dependencies, replace or drop deprecated

### Other changes

- file format for style files are changed from `.postcss.css` to `.css`
- `postcss-modules` was removed
- styles was are bit refactored
- svg icons was optimized
- format of js components changed from `.babel.js` to `.js`

### CODE REVIEW

**Comment by pytkin** [comment]
@legomushroom, @xavierfoucrier can you please review this stuff? 
I'm planning remove gulp and migrate to TS in near feature, just need a bit of your attention (or you can provide an access to write in this repo).

**Comment by xavierfoucrier** [comment]
Hi @pytkin,

Thanks for your interest in this project, unfortunately we have already planned to fully refactor this plugin with the team.

We are conscious that there are a lot of deprecated dependencies inside the mojs player, same for mojs curve editor, and we will give more effort this year to upgrade them. Of course these two plugins are especially used in development environment, and that's why we haven't really work on them these past few years.

Finally, we are only giving write access to Github "Pro" users, or users that already contribute to the mojs project in the past: this is important to keep the mojs ecosystem "clean", and prevent any wrong or side effect modifications.

Thanks again for your time.
Happy coding with mojs :tada:

**Comment by pytkin** [comment]
@xavierfoucrier It is not constructive, what exactly wrong or side effect modifications did you seen in my pull request? I was spend a lot of time to upgrade all the stuff without breaking changes. If you have any suggestions or critics – you are welcome. The only way to “prevent any wrong or side effect modifications” is to review them...
As I see my changes are very similar to your commits in pull request to mojs (v1.0.0). And you just decline this pull request, because, as you say, you want to spend time and do the same work again?
I just want to help, please be open.

**Comment by xavierfoucrier** [comment]
Hi @pytkin,

It is even less constructive to say that this is not constructive...

We are in an open source world here, but open source doesn't mean that all code proposals/refactoring are always merged with the main code. I have reviewed you pull request but I can't approve it. As I said, these core changes has already been discuss with the team and planned. The module is still in development mode as there is no major version published on NPM, so anything can change at any time, that's why it's not productive to approve this kind of pull request.

For now, we are all working on private side projects and can't make mojs our priority: just as a side note, no one here is paid to work on mojs, we are all working in our spare time to maintain the code. With sponsoring and much time dedicated to mojs, probably the v1 could have been published 4 years ago, same for player and curve/timeline editors. If we need help in a near future for TS you will be welcome.

Anyway, if you are hurry to see some changes inside this repository for one of your project and can't wait to see them published/released on NPM, feel free to fork the repository and make your own code modifications.

Thanks for your interest in the project.
Have a nice day! :coffee: :wink:

**Comment by Sandstedt** [comment]
Hi @pytkin, and from my side too, thanks for wanting to contribute to this open source project. I just want to give my side of this too, who is also in the team. Just to hopefully clear thinks up.

Firstly, when you contribute to and open source project, you should never just send a PR out of the blue. That directly create red flags. Because it's all about trust. If we approve code and merge it, we as maintainers are responsible of that code, not you the contributer. The code could be great, like the work it seems like you just did. Or it could contain bugs, API changes that affects related packages, or in a worst case, actually harmful code. So there is a lot of things we need to look after when reviewing someone's PR. That's why it in this scenario, with a PR that come from nowhere, didn't reference any open issues, has a lot of changes in it (123 files) that then needs to be manually reviewed by us in our free time, is not the way to go to contribute unfortunately. So it's not always faster to approve a PR, then to do it ourselves. And this is the case in all open source projects. You can't just write some code to React, create a PR and request it to be merged. It must be well communicated with the core team first, then get an OK from the maintainer to be worked on, so they know who does what.

So hope you can take this as constructive feedback for future contributions. With that said, we could absolute look through your solutions and maybe we could reuse some of them. So your time is not wasted, neither are ours.

All this could also be better formulated in a CONTRIBUTING.md file later on, but we're focused on getting things ready for a v1 release. So please stay with us, raise new issues, join our slack channel to talk to us, and maybe we could assign you some tasks to do, create great animations and hopefully we can together make mojs shine again, as it deserves.

**Pull request closed without merging**
